blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.PostList.as_view(), name = 'index'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('single_page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

single_page/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name="main"),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

single_page/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView

# Create your views here.
class PostList(ListView):
    model = Post
    template_name = 'blog/index.html'

single_page/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'share/base.html')

templates/blog/index.html
<!DOCTYPE html>
{% extends 'share/base.html' %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>민규의 BLOG</title>
</head>
<body>
	{% block content %}
	
	내용입니다. 
    {% endblock %}
</body>
</html>

templates/share/base.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">

    <title>민규</title>
  </head>
  <body>
	  <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="#">MINGYU's SITE</a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><a href="#">About Me</a></li>
                    <li><a href="#">Portfolio</a></li>
                    <li><a href="{% url 'blog:index' %}">Blog</a></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>

    <section class="home">
    </section>
	{% block content %}
    {% endblock %}


<!-- Jquery needed -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>




    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>


  </body>
</html>